#!/usr/bin/env bash
#instructions/commands to install nginx on web server and creating first html
sudo apt-get update
sudo apt install -y nginx ufw

echo "Hello World!" | sudo tee /var/www/html/index.html

mystring="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.trashloop.com\/ permanent;"

sudo sed -i "s/server_name _;/$mystring/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html

myerror="listen 80 default_server;\n\terror_page 404 \/error.html;\n\tlocation = \/error.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$myerror/" /etc/nginx/sites-enabled/default

sudo service nginx restart
