#!/usr/bin/env bash
# Adjust Nginx configuration to listen on port 80

sudo rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default && sudo service nginx start
