#!/usr/bin/env bash
# Bash (init) script "101-manage_my_process" that manages "manage_my_process"

createfile()
{
	echo $$ > /var/run/my_process.pid
}

if [ "$1" == "start" ]
then
	createfile
	./manage_my_process &
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
then 
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
elif [ "$1" == "restart" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	createfile
	./manage_my_process &
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
