#!/usr/bin/env bash
#a Bash script that displays Best School 10 times using while loop with if case
n=1
while [ $n -le 10 ]
do
	if [ $n == 10 ]
	then
		echo "Hi"
	fi
		echo "Best School"
	(( n++ ))
done
